### ISSUE TITLE
Teamwork

### ISSUE THREAD

**Issue by SebGDev** [glassechidna/zxing-cpp#2]
Hello together,

I've some minor bugfixes for the zxing-cpp version to share. Can I add my changes directly to the zxing-cpp repository or should I post it as an issue?

Best regards from germany,
Sebastian

**Comment by Benjamin-Dobell** [comment]
@SebGDev Hi Seb, I see you've just signed up to Github; welcome :smile:

Only members of the "glassechidna" Github organisation can contribute directly to this repo. However, Github has a neat work-flow for submitting pull requests (which appear as both a pull request and issue).

Github has [pretty comprehensive documentation](https://help.github.com/articles/using-pull-requests/) about the process (it's a lot simpler than the amount of documentation would make it seem). Specifically take a look at the "Fork & pull" model mentioned.

**Comment by SebGDev** [comment]
Hi Benjamin, thank you for the fast response and for the documentation. You're right I'am new to GitHub, but I'am getting into it :-).

**Comment by Benjamin-Dobell** [comment]
Thanks for contributing, it's very much appreciated.
