### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by kenny1847** [glassechidna/zxing-cpp#20]
It has a lot of memory leaks from every file it read. I have to read hundreds of barcodes, but after first hundred it crashes with bad_alloc. ~ at 120th barcode it have leaks about 2Gb, so it crashs.

Maybe if I will understand how does this lib works inside I'll try to fix it. But if anybody from porters will solve this problem it will be great

**Comment by kenny1847** [comment]
This issue was solved. I have sent a pull request

**Comment by Benjamin-Dobell** [comment]
Merged
