### ISSUE TITLE
How to run this code ? 

### ISSUE THREAD

**Issue by Jupanlee** [glassechidna/zxing-cpp#40]
I am a newer to ubuntu, I don't know how to run this code. Can anyone tell me how to run it ? Thank you very much!

**Comment by Benjamin-Dobell** [comment]
If you're not comfortable looking through the C++ code to work things out (and honestly I can't blame you), then I'd suggest trying the Ruby gem. It's a lot more straight forward to use - of course it means you'll need to use Ruby.

https://github.com/glassechidna/zxing_cpp.rb

I'm not aware of any documentation existing for the ZXing C++ specifically. Although I'm maintaining this repo, I did not write the code. Of course if once you work things out you'd like to contribute some documentation to the Wiki then that would be very welcome.

I would suggest giving Stackoverflow a shot, there are already a few questions.

**Comment by Jupanlee** [comment]
thank you very much!
