### ISSUE TITLE
Execute multiple instances of zxing binary in parallel?

### ISSUE THREAD

**Issue by logidelic** [glassechidna/zxing-cpp#45]
I read in a previous issue that the library is not thread safe. In my case I'm not making use of the library directly (yet), but instead just executing the zxing binary and eating the output.

If multiple threads may execute zxing processes in parallel, is it still safe? Or does this need to be protected against (presumably because the process make use of some shared resource)?

Thanks.

**Comment by Benjamin-Dobell** [comment]
The library is not thread-safe. However, you can run the library in multiple processes no problems.
