### ISSUE TITLE
transplanted to android platform

### ISSUE THREAD

**Issue by xizi** [glassechidna/zxing-cpp#54]
hi, did you have a tutorial about how transplanted this project to android platform?

**Comment by Benjamin-Dobell** [comment]
If you're targeting Android you might as well using the official ZXing which is Java:
https://github.com/zxing/zxing

**Comment by xizi** [comment]
I'm a c++ programmer, is it possible to transplant this project to android platform?

**Comment by Benjamin-Dobell** [comment]
Well, sure. But it's not recommended, you'd have to build using the NDK cross-compilation tool-chain as you would with any native library on Android.

You're going to have to include Java in your app anyway as Android apps fundamentally run inside a JVM (Dalvik or ART). There's really no good reason not to use the official ZXing repo, it's much more up-to-date and properly maintained. Being a "c++ programmer" isn't a good reason to do _anything_ in c++. Use the right tool for the right job.

**Comment by xizi** [comment]
Thanks for your suggestios 😉, but the c++ may process quickly than java, so i want use the c++ code to build this project in android machine.
