### ISSUE TITLE
Does not make opencv MatSource files

### ISSUE THREAD

**Issue by koziez** [glassechidna/zxing-cpp#55]
Installed on Mac OS X with opencv 2.4.13.2

Did not generate MatSource files. Is there a way to force this?

**Comment by sadransh** [comment]
I think it builds matSource file but it does not put it in includes I just copied matsource.h file to /usr/local/include/zxing folder on my ubuntu and use #include "zxing/MatSource.h" in code.

**Comment by Benjamin-Dobell** [comment]
Closed by #65
