### ISSUE TITLE
ImageReader using jpgd under GPL 3.0 license

### ISSUE THREAD

**Issue by senniraf** [glassechidna/zxing-cpp#69]
Hello,

the class ImageReader is using jpgd which is released under the GPL 3.0 License. This means you cannot release this library under the Apache 2.0 due to the conditions in the GPL License. Can you please change the used jpg decoder?

**Comment by Benjamin-Dobell** [comment]
Errr, which source files or linked libraries do you think are under GPL?

I believe the jpgd files in this repository came from Rich Geldreich's [jpeg-compressor](https://github.com/richgel999/jpeg-compressor) which have clearly been contributed to the public domain. This is indicated both in the repository I've just referenced, and also clearly written at the top of source files themselves:

https://github.com/glassechidna/zxing-cpp/blob/0db7f855135222becff193671faae79c083424b6/cli/src/jpgd.cpp

**Comment by senniraf** [comment]
Oh sorry. You are totally right. I've thought you got this source-file from this project: https://github.com/kornelski/jpeg-compressor.
